# Generated by Django 3.0.8 on 2020-07-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtitle', models.CharField(max_length=100)),
                ('blogdate', models.DateField(auto_now_add=True)),
                ('blogdesc', models.CharField(max_length=300)),
            ],
        ),
    ]
